version: "3"
services:
  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./config/mongo-data:/data/db

  mobius:
    build: ./mock_mobius/
    restart: unless-stopped
    links:
      - mongo

  microservice_websocket:
    build: ./microservice_websocket/
    restart: unless-stopped
    env_file: .env_websocket
    links:
      - mobius
      - mqtt
    ports:
      - 5000:5000
    environment:
      - MOBIUS_URL=http://mobius
      - MOBIUS_PORT=5000
      - MQTT_BROKER_URL=mqtt
      - MQTT_BROKER_PORT=1883
      - MAX_TRESHOLD=7
      - DISABLE_MQTT=false
    networks:
      - default
      - proxy

networks:
  default:
    driver: bridge
  proxy:
    name: nginx-proxy
