version: "3"
services:
  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./config/passwords:/passwords:ro
    ports:
      - 1884:1884

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./config/mongo-data:/data/db

  mobius:
    build: ./mock_mobius/
    restart: unless-stopped
    links:
      - mongo

  mobius_adapter:
    build: ./mobius_adapter/
    restart: unless-stopped
    links:
      - mqtt
      - mobius
    environment:
      - DEBUG=1

  backend:
    build: ./backend/
    restart: unless-stopped
    env_file: .env_websocket
    links:
      - mqtt
    ports:
      - 8000:8000
