version: "3"
services:
  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  cache:
    build: ./cache
    restart: unless-stopped
    volumes:
      - ./cache/data:/data

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./config/mongo-data:/data/db

  mobius:
    build: ./mock_mobius/
    restart: unless-stopped
    links:
      - mongo

  mobius_adapter:
    build: ./mobius_adapter/
    restart: unless-stopped

  microservice_websocket:
    build: ./microservice_websocket/
    restart: unless-stopped
    env_file: .env_websocket
    links:
      - mobius
      - mqtt
      - cache
    ports:
      - 5000:5000
    networks:
      - default
      - proxy

networks:
  default:
    driver: bridge
  proxy:
    name: nginx-proxy
