settings:
  node_info:
    organizationID: ""
    applicationID: ""
    sensorID: 1
  microservice:
    url: "http://localhost"
    port: 5000
    api_key: "verysecret"
  mqtt:
    url: "localhost"
    port: 1883
  mobius:
    sensorId: ""
    sensorPath: ""
