settings:
  node_info:
    organizationID: ""
    applicationID: ""
    nodeID: 1
    nodeName: "Nodo1"
  microservice:
    url: "http://localhost"
    port: 5000
    api_key: "verysecret"
    keep_alive_seconds: 30
  mqtt:
    url: "localhost"
    port: 1883
  can:
    bustype: 'socketcan'
    channel: 'can0'
    bitrate: 12500
