settings:
  node_info:
    organizationID: ""
    applicationID: ""
    nodeID: 1
    nodeName: "Nodo1"
  mqtt:
    url: "irma.monema.dev"
    port: 1884
    tls: true
    user: "admin"
    password: "admin"
    keep_alive_seconds: 30
  can:
    bustype: "socketcan"
    channel: "can0"
    bitrate: 20000
    filter_id: 96
    filter_mask: 248
