settings:
  node_info:
    organizationID: ""
    applicationID: ""
    nodeID: 1
    nodeName: "Nodo1"
  microservice:
    url: "https://irma.monema.dev"
    port: 443
    api_key: "verysecret"
    keep_alive_seconds: 30
  mqtt:
    url: "irma.monema.dev"
    port: 1884
    user: "admin"
    password: "admin"
  can:
    bustype: "socketcan"
    channel: "can0"
    bitrate: 12500
