flowchart TD;

msw[microservice_websocket]
mm[mock_mobius]
irma-ui[Irma UI]
mqtt[Broker MQTT]
redis[Redis]
mongo[(MongoDB)]

nodo[Nodo]
rilevatori[Rilevatori]

msw -- HTTP 5000 --> mm
msw -- MONGO 27017 --> mongo
mm -- MONGO 27017 --> mongo
irma-ui -- HTTP 5000 --> msw
nodo -- HTTP 5000 --> msw
irma-ui <-- WEBSOCKET 5000 --> msw
rilevatori <-- CAN --> nodo
msw -- REDIS 6379 --> redis

msw -- PUB --> mqtt
nodo -- SUB --> mqtt
