flowchart TD;

mongo[(MongoDB)]
b[backend]
mobius[Mobius]
ma[mobius_adapter]
irma-ui[Irma UI]
mqtt[Broker MQTT]

nodo[Nodo]
rilevatori[Rilevatori]

b -- MONGO 27017 --> mongo
ma --> mobius
irma-ui -- HTTP 5000 --> b
b -- WEBSOCKET 5000 --> irma-ui
rilevatori <-- CAN --> nodo

b <-- PUB/SUB 1884 --> mqtt
nodo <-- PUB/SUB 1884 --> mqtt
mqtt -- SUB 1884 --> ma
