flowchart TD;

mongo[(MongoDB)]
b[backend]
mobius[Mobius]
ma[mobius_adapter]
irma-ui[Irma UI]
mqtt[Broker MQTT]

iot[IoT Device]

b -- MONGO 27017 --> mongo
ma --> mobius
irma-ui -- HTTP 5000 --> b
b -- WEBSOCKET 5000 --> irma-ui

b <-- PUB/SUB 1884 --> mqtt
iot <-- PUB/SUB 1884 --> mqtt
mqtt -- SUB 1884 --> ma
