flowchart TD;

msw[microservice_websocket]
mobius[Mobius]
ma[mobius_adapter]
irma-ui[Irma UI]
mqtt[Broker MQTT]
redis[Redis]
mongo[(MongoDB)]

iot[IoT Device]

msw -- POST 5000 --> ma
ma --> mobius
msw -- MONGO 27017 --> mongo
irma-ui -- HTTP 5000 --> msw
iot -- HTTP 5000 --> msw
irma-ui <-- WEBSOCKET 5000 --> msw
msw -- REDIS 6379 --> redis

msw -- PUB --> mqtt
iot -- SUB --> mqtt
